# Generated by Django 4.1.2 on 2022-10-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
    ]
