# Generated by Django 4.1.2 on 2022-10-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=30, null=True, verbose_name='тип номера')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='цена за номер в USD')),
            ],
            options={
                'verbose_name': 'тип номера',
                'verbose_name_plural': 'типы номеров',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер')),
                ('room_image', models.ImageField(upload_to='rooms_pics')),
                ('room_image_2', models.ImageField(blank=True, null=True, upload_to='rooms_pics')),
                ('room_image_3', models.ImageField(blank=True, null=True, upload_to='rooms_pics')),
                ('room_image_4', models.ImageField(blank=True, null=True, upload_to='rooms_pics')),
                ('capacity', models.IntegerField(verbose_name='количество гостей')),
                ('number_of_beds', models.IntegerField(verbose_name='количество кроватей')),
                ('description', models.TextField(verbose_name='краткое описание')),
                ('room_tv', models.CharField(choices=[('NONE', 'Нет'), ('FLAT TV', 'Flat TV'), ('FLAT LED TV', 'Flat Led TV')], default='NONE', max_length=20, verbose_name='наличие тв')),
                ('room_wifi', models.CharField(choices=[('NOT AVAILABLE', 'Нет'), ('AVAILABLE', 'Есть')], default='NOT AVAILABLE', max_length=20, verbose_name='наличие wi-fi')),
                ('room_cond', models.CharField(choices=[('NOT AVAILABLE', 'Нет'), ('AVAILABLE', 'Есть')], default='NOT AVAILABLE', max_length=30, verbose_name='наличие кондиционера')),
                ('room_bathroom', models.CharField(choices=[('ATTACHED', 'Есть'), ('NOT ATTACHED', 'Нет')], default='ATTACHED', max_length=30, verbose_name='наличие ванной, душевой')),
                ('status_reservation', models.BooleanField(default=False)),
                ('rating_stars', models.IntegerField(blank=True, default=0, null=True, verbose_name='рейтинг')),
                ('best_choice', models.BooleanField(default=False, verbose_name='рекомендация администрации')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.type', verbose_name='цена и тип номера')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'номера',
                'ordering': ['number'],
            },
        ),
    ]
