# Generated by Django 4.1.2 on 2022-10-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'тип номера', 'verbose_name_plural': 'типы номеров'},
        ),
    ]
