# Generated by Django 4.1.2 on 2022-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_type_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='цена за номер в USD'),
        ),
    ]
