# Generated by Django 4.1.2 on 2022-10-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_type_price_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
