# Generated by Django 4.1.2 on 2022-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='short_desc',
            field=models.CharField(blank=True, default='None', max_length=30, null=True, verbose_name='тип номера'),
        ),
    ]
