# Generated by Django 4.1.2 on 2022-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_type_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
