# Generated by Django 4.1.2 on 2022-10-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('mini_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='мини заголовок')),
                ('body', models.TextField(blank=True, verbose_name='текст новости')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.cat', verbose_name='категория новостей')),
            ],
        ),
    ]
