# Generated by Django 4.1.2 on 2022-10-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
