# Generated by Django 4.1.2 on 2022-10-21 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options'),
        ('rooms', '0006_room_slug'),
        ('bookings', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-reservation_date'], 'verbose_name': 'бронирование номеров', 'verbose_name_plural': 'бронирование номеров'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateField(null=True, verbose_name='с'),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='примечание'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='количество гостей'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время бронирование'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='перечень занятых дней'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.DateField(null=True, verbose_name='по'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='всего дней'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='гость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='номер'),
        ),
    ]
